### ISSUE TITLE
Tar Options Tweak

### ISSUE THREAD

**Issue by gordboy** [luk1337/gts4lv-fw#2]
Hello this is a wonderful resource, thank you for providing this.

There is a small improvement could be made in regard to the options to `tar`.

At present you use default options and delete the unwanted items from AP and BL files.

Better yet would be to unpack the AP and BL files completely, and repack the required files using something like

```
tar --create --format=gnu -b20 --quoting-style=escape --owner=0 --group=0 --totals --mode=644  -f AP.tar modem.bin.lz4
md5sum AP.tar >> AP.tar
mv AP.tar AP.tar.md5
```

The BL file is almost the same except it has something like

```
tar --create --format=gnu -b20 --quoting-style=escape --owner=0 --group=0 --totals --mode=644  -f BL.tar abl.elf.lz4 xbl.elf.lz4 xbl_config.elf.lz4 tz.mbn.lz4 hyp.mbn.lz4 devcfg.mbn.lz4 aop.mbn.lz4 cmnlib.mbn.lz4 cmnlib64.mbn.lz4 keymaster64.mbn.lz4 vaultkeeper.mbn.lz4 qupv3fw.elf.lz4 sec.dat.lz4 apdp.mbn.lz4 msadp.mbn.lz4 bksecapp.mbn.lz4 storsec.mbn.lz4 NON-HLOS.bin.lz4 dspso.bin.lz4
md5sum BL.tar >> BL.tar
mv BL.tar BL.tar.md5
```

I used short AP and BL names to save space here, but you would probably use the original long names.

This has the benefit of making the files belong to "root" instead of some random user, and it explicitly uses uses known good options, instead of accepting whatever Samsung originally used in creating the archives.

I did this on my own SM-T720 device and flashed it in Odin - all good, since LineageOS 18.1 was already installed. And I put the "old" CUA3 version back in afterwards to revert to how it was before - all good. Not sure if there is much actual difference between these CUA3 and DUD3 versions to be honest, but nothing broke going up or down.

BTW when will you be updating your excellent LineageOS 18.1 ROM for SM-T720 (gts4lvwifi) to allow (or even require) the latest Samsung firmware?

**Comment by luk1337** [comment]
I don't really think repacking archives is worth the hassle. After all, Samsung specifically packaged them to use with Odin so repacking them is not going to make any difference whatsoever for it. It also saves us from having to either hardcode each package's contents or generate it on runtime.

>BTW when will you be updating your excellent LineageOS 18.1 ROM for SM-T720 (gts4lvwifi) to allow (or even require) the latest Samsung firmware?

Unknown, kernel source is still not available.

**Comment by gordboy** [comment]
Thanks for your prompt and succinct answer. Now closing issue.
